version: '3.8'
services:
  api-app:
    image: arian-blazor-app:latest
    build:
      dockerfile: apiWebUI/Dockerfile
    ports:
      - "5004:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      DefaultConnection: /run/secrets/APIBaseUrl # Reference the secret file
    secrets:
      - APIBaseUrl
    deploy:
      restart_policy:
        condition: on-failure

secrets:
  APIBaseUrl:
    external: true  # Use the secret created in Portainer
